### ISSUE TITLE
Negative Number Sorting

### ISSUE THREAD

**Issue by rpzatkoff** [nwoltman/string-natural-compare#1]
If you are sorting negative numbers, -100 is smaller than -1, and should come first in the sort.

The unit test [here](https://github.com/nwoltman/string-natural-compare/blob/master/test/test.js#L171)
```
[-1, 1, -2, 2, -10, 10, -11, 11, -100, 100]
      .sort(naturalCompare)
      .should.deepEqual([-1, -2, -10, -11, -100, 1, 2, 10, 11, 100]);
```

show that although all negative integers come before all positives, they are in reverse order.

The result should be.
```
[-1, 1, -2, 2, -10, 10, -11, 11, -100, 100]
      .sort(naturalCompare)
      .should.deepEqual([-100, -11, -10, -2, -1, 1, 2, 10, 11, 100]);

```

**Comment by nwoltman** [comment]
This is actually on purpose. The sorting algorithm doesn't count the minus sign `-` as being part of the number. I'll admit that that test is a little misleading since it uses numbers instead of strings (so I might end up changing it) but if you look at [the test above that one](https://github.com/nwoltman/string-natural-compare/blob/master/test/test.js#L165-L167), you'll see a better example of why this is.

If you include the minus sign as part of the number (meaning the number is negative), you'd get this:

```
file-20.txt
file-3.txt
file-2.txt
file-1.txt
```

whereas someone who names files in that way probably wanted them to be ordered like this:

```
file-1.txt
file-2.txt
file-3.txt
file-20.txt
```

This is the same way that PHP's [strnatcmp()](http://php.net/manual/en/function.strnatcmp.php) and [natsort()](http://php.net/manual/en/function.natsort.php#example-5655) functions operate.

**Comment by nwoltman** [comment]
f429139f855530da816ec9285b8c158b1c1f18bf should clear things up a bit.

**Comment by rpzatkoff** [comment]
That type of sorting makes sense for the case you are describing.  My use for the sort function is actually through [http://listjs.com/api/](list.js) - and so it is sorting any column that includes negative numbers. it does it backwards.

my suggestion is to keep the method of sorting you are currently doing when you have 

```
<some_text>-<number>
```

but when you have just the number that starts with the dash - then treat it in reverse as a negative number.

**Comment by nwoltman** [comment]
Unfortunately comparing strings in that fashion that may not work for everyone. Comparing numbers as negatives is usually not a part of natural sorting algorithms, including JavaScript's built-in "natural" comparison algorithm:

```js
'-2'.localeCompare('-10', 'en', {numeric: true}) === -1
```

I'm wondering if there may be a better solution to your problem. Are all of the strings in the column you're sorting numbers? If so, it looks like you could use the `sortFunction` option with a function that's similar to the standard number sorting function: `(a, b) => a - b`.
