### ISSUE TITLE
Handle alphabets, that have double letters

### ISSUE THREAD

**Issue by gyula-s** [nwoltman/string-natural-compare#12]
I'm trying to sort some strings, based on the Hungarian alphabet, but the problem that I'm facing right now, is that the hungarian alphabet has double and triple letter combos, that need to be handled separately.
Such letters are `cs`, `dz`,`dzs`,`sz`,`ty`, `zs`... and their order in the alphabet are like ```a á b c cs ...```

for example the following words: ```cápa, csak, cifra, sima, combos``` would need to be sorted like ```cápa, cifra, csak, combos, sima``` 

maybe if I could provide an array (or a prepared index map) for the alphabet, instead of a string, we could override the expected behaviour.

**Comment by nwoltman** [comment]
Hey @soosgyul. Sorry for taking so long to get to this issue. I think that is a pretty complicated problem and is outside of the scope of this module. It looks to me like solving this would require looking ahead in the strings and checking multiple letters rather than just comparing single letters (as this module currently does). That kind of solution is pretty unique and I think it would be better off as a separate module rather than trying to add that functionality into this module.
