### ISSUE TITLE
Can't handle decimal digest correctly 

### ISSUE THREAD

**Issue by vaxul** [nwoltman/string-natural-compare#13]
Hi,

I tried the following with the latest version:
```js
const naturalCompare = require('string-natural-compare');

const test1 = ['5', '-1', '0.5', '-0.6', '0.001', '-0.002', '-0.004'];
console.log('test1 before:', test1.join(' ; '));
// test1 before: 5 ; -1 ; 0.5 ; -0.6 ; 0.001 ; -0.002 ; -0.004
test1.sort(naturalCompare);
console.log('test1 after:', test1.join(' ; '));
// test1 after: -0.002 ; -0.004 ; -0.6 ; -1 ; 0.001 ; 0.5 ; 5

const test2 = ['5', '-1', '0,5', '-0,6', '0,001', '-0,002', '-0,004'];
console.log('test2 before:', test2.join(' ; '));
// test2 before: 5 ; -1 ; 0,5 ; -0,6 ; 0,001 ; -0,002 ; -0,004
test2.sort(naturalCompare);
console.log('test2 after:', test2.join(' ; '));
// test2 after: -0,002 ; -0,004 ; -0,6 ; -1 ; 0,001 ; 0,5 ; 5
```

What I would expect is: 
-0,004 ; -0,002 ; -0,6 ; -1 ; 0,001 ; 0,5 ; 5

Is this possible?

**Comment by nwoltman** [comment]
No not really. It's not possible to sort negative numbers because a `-` character doesn't always mean the number is negative. For example, consider this set of strings:

```
a-1.jpg
a-2.jpg
a-3.jpg
```

Normally I'd expect them to be sorted to `a-1.jpg ; a-2.jpg ; a-3.jpg`, but if the algorithm assumes the `-` character turns the number negative, then the output would be `a-3.jpg ; a-2.jpg ; a-1.jpg`, which is not actually what we want in this case.

I say "not really" because there could be an option like `{ dashMeansNegative: true }` that you could pass to the function to tell it you always want `-` before a number to mean it's negative. However, I think that would be out of scope for this package because an algorithm to handle negative numbers would probably need to be a completely new function since it would require a bunch of new code, so it might as well be a different package.

Also, if your input actually is just an array of numbers as strings, you might as well convert them to actual numbers using `Number()` or `Number.parseFloat()` and then sort the array.

**Comment by vaxul** [comment]
Thanks for your response and the hint. I will look into it. :)
